name: Deploy
run-name: Deploy code to release branch
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
      - name: NPM install
        run: npm ci
      - name: show all branches
        run: git branch -a
      - name: build code
        run: npm run build
      - name: force files
        run: git add -f dist
      - name: push code
        run: |
          git config --global user.email "hun0895@gmail.com"
          git config --global user.name "Hung Le"
          git commit -am "automation build code"
          git checkout -b develop
          git push -f origin develop
